# Autogenerated script from write_trimmomatic_script.R
# date Thu Sep  1 13:05:35 2016
# make sure directory paths exist before running script
#### trimmomatic input K1-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K1-1st_S021_R1_.fastq.gz input/K1-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K1-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K1-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K1-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K1-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K2-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K2-1st_S021_R1_.fastq.gz input/K2-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K2-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K2-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K2-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K2-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K3-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K3-1st_S021_R1_.fastq.gz input/K3-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K3-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K3-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K3-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K3-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K4-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K4-1st_S021_R1_.fastq.gz input/K4-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K4-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K4-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K4-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K4-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K5-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K5-1st_S021_R1_.fastq.gz input/K5-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K5-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K5-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K5-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K5-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K6-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K6-1st_S021_R1_.fastq.gz input/K6-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K6-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K6-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K6-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K6-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K7-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K7-1st_S021_R1_.fastq.gz input/K7-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K7-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K7-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K7-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K7-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K8-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K8-1st_S021_R1_.fastq.gz input/K8-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_K8-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K8-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_K8-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K8-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N1-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N1-1st_S021_R1_.fastq.gz input/N1-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_N1-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N1-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_N1-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N1-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N2-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N2-1st_S021_R1_.fastq.gz input/N2-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_N2-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N2-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_N2-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N2-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N3-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N3-1st_S021_R1_.fastq.gz input/N3-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_N3-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N3-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_N3-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N3-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N4-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N4-1st_S021_R1_.fastq.gz input/N4-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_N4-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N4-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_N4-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N4-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N5-1st 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N5-1st_S021_R1_.fastq.gz input/N5-1st_S021_R2_.fastq.gz output/Trimmed/S021/trim_N5-1st_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N5-1st_S021_R1_.fastq.gz output/Trimmed/S021/trim_N5-1st_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N5-1st_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K1-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K1-2nd_S021_R1_.fastq.gz input/K1-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K1-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K1-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K1-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K1-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K2-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K2-2nd_S021_R1_.fastq.gz input/K2-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K2-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K2-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K2-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K2-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K3-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K3-2nd_S021_R1_.fastq.gz input/K3-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K3-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K3-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K3-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K3-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K4-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K4-2nd_S021_R1_.fastq.gz input/K4-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K4-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K4-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K4-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K4-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K5-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K5-2nd_S021_R1_.fastq.gz input/K5-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K5-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K5-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K5-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K5-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K6-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K6-2nd_S021_R1_.fastq.gz input/K6-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K6-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K6-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K6-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K6-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K7-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K7-2nd_S021_R1_.fastq.gz input/K7-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K7-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K7-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K7-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K7-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input K8-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/K8-2nd_S021_R1_.fastq.gz input/K8-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_K8-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_K8-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_K8-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_K8-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N1-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N1-2nd_S021_R1_.fastq.gz input/N1-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_N1-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N1-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_N1-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N1-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N2-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N2-2nd_S021_R1_.fastq.gz input/N2-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_N2-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N2-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_N2-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N2-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N3-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N3-2nd_S021_R1_.fastq.gz input/N3-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_N3-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N3-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_N3-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N3-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N4-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N4-2nd_S021_R1_.fastq.gz input/N4-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_N4-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N4-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_N4-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N4-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N5-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N5-2nd_S021_R1_.fastq.gz input/N5-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_N5-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N5-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_N5-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N5-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input N6-2nd 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/N6-2nd_S021_R1_.fastq.gz input/N6-2nd_S021_R2_.fastq.gz output/Trimmed/S021/trim_N6-2nd_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_N6-2nd_S021_R1_.fastq.gz output/Trimmed/S021/trim_N6-2nd_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_N6-2nd_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input SK167 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/SK167_S021_R1_.fastq.gz input/SK167_S021_R2_.fastq.gz output/Trimmed/S021/trim_SK167_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_SK167_S021_R1_.fastq.gz output/Trimmed/S021/trim_SK167_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_SK167_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input SK175 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/SK175_S021_R1_.fastq.gz input/SK175_S021_R2_.fastq.gz output/Trimmed/S021/trim_SK175_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_SK175_S021_R1_.fastq.gz output/Trimmed/S021/trim_SK175_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_SK175_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



#### trimmomatic input SK178 

java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar PE -phred33 input/SK178_S021_R1_.fastq.gz input/SK178_S021_R2_.fastq.gz output/Trimmed/S021/trim_SK178_S021_R1_.fastq.gz output/Trimmed/S021/Unpaired/up_SK178_S021_R1_.fastq.gz output/Trimmed/S021/trim_SK178_S021_R2_.fastq.gz output/Trimmed/S021/Unpaired/up_SK178_S021_R2_.fastq.gz ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36



