# File: write_trimmomatic_script.R
# Auth: umar.niazi@kcl.as.uk
# DESC: create a shell script to run trimmomatic on each sample
# Date: 01/09/2016


## set variables and source libraries
gcswd = getwd()
setwd('Keloid_main/')

## connect to mysql database to get sample information
library('RMySQL')

##### connect to mysql database to get samples
db = dbConnect(MySQL(), user='rstudio', password='12345', dbname='Projects', host='127.0.0.1')
dbListTables(db)

# check how many files each sample has
q = paste0('select count(File.idSample) as files, Sample.idData, Sample.title, Sample.id as SampleID from File, Sample
           where (Sample.idData = 2 and File.idSample = Sample.id) group by File.idSample')
dfQuery = dbGetQuery(db, q)
dfQuery$title = gsub(" ", "", dfQuery$title, fixed = T)

# for each sample id, get the corresponding files
cvQueries = paste0('select File.*, Sample.title from File, Sample 
           where (Sample.idData = 2 and Sample.id =', dfQuery$SampleID, ') and (File.idSample = Sample.id) and 
                   File.group1 like "S021"')
## change this File.group1 to S021 or S014 depending on sequencing run

# set the directory names for trimmomatic
cvInput = 'input/'
cvOutput = 'output/Trimmed/S021/'
cvOutput.unpaired = paste0(cvOutput, 'Unpaired/')
cvTrimmomatic = '/opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar'
cvIlluminaAdap = '/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa'
# create a shell script
dir.create('AutoScripts')
oFile = file('AutoScripts/trimmomatic_S021.sh', 'wt')

writeLines(c('# Autogenerated script from write_trimmomatic_script.R', paste('# date', date())), oFile)
writeLines(c('# make sure directory paths exist before running script'), oFile)

temp = sapply(cvQueries, function(x){
  # get the file names
  dfFiles = dbGetQuery(db, x)
  # remove white space from title
  dfFiles$title = gsub(" ", "", dfFiles$title, fixed=T)
  # split the file names into paired end 1 and 2, identified by R1 and R2 in the file name
  f = dfFiles$name
  d = grepl('_R1_', f)
  d = as.character(d)
  d[d == 'TRUE'] = 'R1'
  d[d == 'FALSE'] = 'R2'
  lf = split(f, d)
  # write trimmomatic command
  in.r1 = paste0(cvInput, lf[[1]])
  in.r2 = paste0(cvInput, lf[[2]])
  out.r1 = paste0(cvOutput, 'trim_', lf[[1]])
  out.r2 = paste0(cvOutput, 'trim_', lf[[2]])
  out.r1.up = paste0(cvOutput.unpaired, 'up_', lf[[1]])
  out.r2.up = paste0(cvOutput.unpaired, 'up_', lf[[2]])
  p1 = paste('java -jar', cvTrimmomatic, 'PE -phred33', in.r1, in.r2, out.r1, out.r1.up, out.r2, out.r2.up, sep=' ')
  p2 = paste0('ILLUMINACLIP:', cvIlluminaAdap, ':2:30:10:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36')
  com = paste(p1, p2, sep=' ')
  writeLines(paste('#### trimmomatic input', dfFiles$title[1], '\n'), oFile)
  writeLines(com, oFile)
  writeLines('\n\n', oFile)
})

close(oFile)
dbDisconnect(db)


